"""
core/auto_demo.py
=================
TỰ ĐỘNG TẠO SẢN PHẨM MẪU (AUTO-DEMO GENERATOR)
==============================================
Khi AURA phát hiện 1 tin việc Freelance (Scraping, Scripting, Content),
module này tự động phân tích yêu cầu và TẠO NGAY MỘT BẢN DEMO THẬT
(File CSV mẫu, Python Script mẫu, hoặc Markdown mẫu) để đính kèm vào Pitch!
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Any

from core.config import settings

logger = logging.getLogger("aura.auto_demo")


def analyze_job_task_type(title: str, description: str) -> str:
    """Phân loại công việc: 'scraping', 'automation', 'content', 'video', hoặc 'general'."""
    text = f"{title} {description}".lower()

    if any(k in text for k in ("scrape", "crawl", "bóc tách", "trích xuất", "csv", "excel", "data collection")):
        return "scraping"
    if any(k in text for k in ("python", "script", "automation", "tự động hóa", "bot", "api", "tool")):
        return "automation"
    if any(k in text for k in ("dịch", "translate", "viết bài", "article", "summary", "tóm tắt", "markdown")):
        return "content"
    if any(k in text for k in ("video", "sub", "phụ đề", "capcut", "lồng tiếng", "dubbing")):
        return "video"
    return "general"


def _cloud_call(system: str, user: str, max_tokens: int = 1500) -> str:
    """Gọi Cloud Engine để tự động sinh nội dung demo."""
    try:
        from core.llm import CloudEngine
        res = CloudEngine().complete(
            [{"role": "user", "content": user}],
            system_prompt=system,
            temperature=0.3,
            max_tokens=max_tokens,
            tier="fast",
        )
        if res.get("ok"):
            return str(res.get("text", "")).strip()
    except Exception as exc:  # noqa: BLE001
        logger.warning("Gọi cloud sinh demo lỗi: %s", exc)
    return ""


def generate_sample_demo(title: str, description: str, target_dir: Path) -> dict[str, Any]:
    """Phân tích tin việc và tạo ngay 1 file sản phẩm mẫu (Demo Output) trong target_dir.

    Returns:
        dict: metadata về demo đã tạo (file_path, task_type, preview_text)
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    task_type = analyze_job_task_type(title, description)
    logger.info("Auto-Demo: Bắt đầu tạo demo cho job '%s' (Loại: %s)...", title[:50], task_type)

    demo_file: Path | None = None
    preview_text = ""

    if task_type == "scraping":
        system = (
            "Bạn là chuyên gia DATA SCRAPING. Hãy tạo ra DỮ LIỆU MẪU MÔ PHỎNG (5 bản ghi CSV) "
            "phù hợp nhất với yêu cầu công việc. Trả về ĐÚNG định dạng CSV (có header, không markdown)."
        )
        csv_content = _cloud_call(system, f"Tên việc: {title}\nMô tả: {description[:1000]}")
        if not csv_content or "," not in csv_content:
            csv_content = "id,title,price,status,scraped_at\n1,Sample Item A,$19.99,In Stock,2026-07-24\n2,Sample Item B,$29.99,In Stock,2026-07-24\n"

        demo_file = target_dir / "demo_output.csv"
        demo_file.write_text(csv_content.strip(), encoding="utf-8")
        preview_text = "\n".join(csv_content.strip().split("\n")[:4])

    elif task_type == "automation":
        system = (
            "Bạn là lập trình viên Python Automation xuất sắc. Hãy viết MỘT SCRIPT PYTHON MẪU "
            "(sạch sẽ, dùng requests/BeautifulSoup/std libs, có docstring & hàm main hoàn chỉnh) "
            "giải quyết một phần lõi của yêu cầu công việc. CHỈ trả về code Python."
        )
        py_content = _cloud_call(system, f"Tên việc: {title}\nMô tả: {description[:1000]}")
        py_content = re.sub(r"^```(?:python)?|```$", "", py_content.strip(), flags=re.M).strip()
        if not py_content:
            py_content = '#!/usr/bin/env python3\n"""Demo Automation Script generated by AURA."""\nimport requests\n\ndef run():\n    print("AURA Demo Automation Task Executed Successfully.")\n\nif __name__ == "__main__":\n    run()\n'

        demo_file = target_dir / "demo_script.py"
        demo_file.write_text(py_content, encoding="utf-8")
        preview_text = "\n".join(py_content.split("\n")[:8])

    else:
        system = (
            "Bạn là chuyên gia biên tập nội dung. Hãy tạo một ĐOẠN VĂN MẪU / TÓM TẮT MẪU "
            "(chuẩn Markdown, khoảng 100-150 từ) thể hiện năng lực cho công việc sau."
        )
        md_content = _cloud_call(system, f"Tên việc: {title}\nMô tả: {description[:1000]}")
        if not md_content:
            md_content = f"# Demo Output for {title}\n\n*AURA generated sample demonstration for client review.*"

        demo_file = target_dir / "demo_sample.md"
        demo_file.write_text(md_content, encoding="utf-8")
        preview_text = md_content[:200]

    result = {
        "task_type": task_type,
        "demo_file": str(demo_file) if demo_file else "",
        "filename": demo_file.name if demo_file else "",
        "preview_text": preview_text,
    }

    info_path = target_dir / "demo_info.json"
    info_path.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    return result
